### ISSUE TITLE
SomethingNew

### ISSUE THREAD

**Issue by d-cook** [enkiv2/misc#2]
Hey, I just stumbled upon your posts on Medium about composable GUIs and the history of GUI software from PARC on through Apple.

I am part of a collaboration that I believe has much of the same goals and ideas (and context of history from PARC) as you present. Our individual goals are to fix the messed up state of software and further the original vision of the likes of Kay & Engelbart. Our goal as a collaboration is to connect as many such individuals and organizations as possible, so we can share ideas and inspiration and perspective, because working in a bubble is not likely to succeed.

Come have a look (and also see what I'm doing in my personal projects to help): https://github.com/d-cook/SomethingNew

I'll also recommend you to Joel's blog. Here's a good one to start with: http://programmingmadecomplicated.wordpress.com/2017/10/29/introducing-drw-a-useful-tool-to-solve-a-practical-problem/

**Comment by enkiv2** [comment]
Thanks, I'll take a look
